### ISSUE TITLE
restart the container "jobmanager"

### ISSUE THREAD

**Issue by progyoung** [pinpoint-apm/pinpoint-docker#152]
As I restart the container jobmanager,  an error occurs:
```
pinpoint-flink-jobmanager  |  The program finished with the following exception:
pinpoint-flink-jobmanager  |
pinpoint-flink-jobmanager  | org.apache.flink.client.program.ProgramInvocationException: No manifest found in jar file '/opt/flink/pinpoint-flink-job.jar'. The manifest is need to point to the program's main class.
pinpoint-flink-jobmanager  |    at org.apache.flink.client.program.PackagedProgram.getEntryPointClassNameFromJar(PackagedProgram.java:420)
pinpoint-flink-jobmanager  |    at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:158)
pinpoint-flink-jobmanager  |    at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:65)
pinpoint-flink-jobmanager  |    at org.apache.flink.client.program.PackagedProgram$Builder.build(PackagedProgram.java:691)
pinpoint-flink-jobmanager  |    at org.apache.flink.client.cli.CliFrontend.buildProgram(CliFrontend.java:851)
pinpoint-flink-jobmanager  |    at org.apache.flink.client.cli.CliFrontend.getPackagedProgram(CliFrontend.java:271)
pinpoint-flink-jobmanager  |    at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:245)
pinpoint-flink-jobmanager  |    at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
pinpoint-flink-jobmanager  |    at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
pinpoint-flink-jobmanager  |    at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:28)
pinpoint-flink-jobmanager  |    at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
```

**Comment by ga-ram** [comment]
@progyoung Thank you for your contribution 👍
